# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
## .pre-commit-config.yaml
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
# See https://pre-commit.com/hooks.html for more hooks
-   repo: https://github.com/astral-sh/ruff-pre-commit
# Ruff version.
    rev: v0.2.2
    hooks:
    # Run the linter.
    - id: ruff
      types_or: [ python, pyi, jupyter ]
      args: [ --fix ]
    # Run the formatter.
    - id: ruff-format
      types_or: [ python, pyi, jupyter ]
