[project]
authors = ["Charles Duarte <140444382+linduarte@users.noreply.github.com>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "web-scraper"
platforms = ["win-64"]
version = "0.1.0"

[tasks]

[dependencies]
